export interface RevisionesCounts {
  pending: number;
  approved: number;
  rejected: number;
  penal: number;
  etica: number;
  news: number;
  legal: number;
}

export const CANONICAL_REGIONS = [
  "Amazonas",
  "Áncash",
  "Apurímac",
  "Arequipa",
  "Ayacucho",
  "Cajamarca",
  "Callao",
  "Cusco",
  "Huancavelica",
  "Huánuco",
  "Ica",
  "Junín",
  "La Libertad",
  "Lambayeque",
  "Lima",
  "Loreto",
  "Madre de Dios",
  "Moquegua",
  "Pasco",
  "Piura",
  "Puno",
  "San Martín",
  "Tacna",
  "Tumbes",
  "Ucayali",
] as const;

export const REGION_ROOT_DISTRICTS: Record<string, string[]> = {
  Amazonas: ["AMAZONAS"],
  Áncash: ["ANCASH"],
  Ancash: ["ANCASH"],
  Apurímac: ["APURIMAC"],
  Apurimac: ["APURIMAC"],
  Arequipa: ["AREQUIPA"],
  Ayacucho: ["AYACUCHO"],
  Cajamarca: ["CAJAMARCA"],
  Callao: ["CALLAO"],
  Cusco: ["CUSCO"],
  Huancavelica: ["HUANCAVELICA"],
  Huánuco: ["HUANUCO"],
  Huanuco: ["HUANUCO"],
  Ica: ["ICA"],
  Junín: ["JUNIN"],
  Junin: ["JUNIN"],
  "La Libertad": ["LA LIBERTAD"],
  Lambayeque: ["LAMBAYEQUE"],
  Lima: ["LIMA METROPOLITANA", "LIMA PROVINCIAS", "LIMA"],
  Loreto: ["LORETO"],
  "Madre de Dios": ["MADRE DE DIOS"],
  Moquegua: ["MOQUEGUA"],
  Pasco: ["PASCO"],
  Piura: ["PIURA"],
  Puno: ["PUNO"],
  "San Martín": ["SAN MARTIN"],
  "San Martin": ["SAN MARTIN"],
  Tacna: ["TACNA"],
  Tumbes: ["TUMBES"],
  Ucayali: ["UCAYALI"],
};

export const ROOT_DISTRICT_TO_REGION: Record<string, string> = {
  AMAZONAS: "Amazonas",
  ANCASH: "Áncash",
  APURIMAC: "Apurímac",
  AREQUIPA: "Arequipa",
  AYACUCHO: "Ayacucho",
  CAJAMARCA: "Cajamarca",
  CALLAO: "Callao",
  CUSCO: "Cusco",
  HUANCAVELICA: "Huancavelica",
  HUANUCO: "Huánuco",
  ICA: "Ica",
  JUNIN: "Junín",
  "LA LIBERTAD": "La Libertad",
  LAMBAYEQUE: "Lambayeque",
  "LIMA METROPOLITANA": "Lima",
  "LIMA PROVINCIAS": "Lima",
  LIMA: "Lima",
  LORETO: "Loreto",
  "MADRE DE DIOS": "Madre de Dios",
  MOQUEGUA: "Moquegua",
  PASCO: "Pasco",
  PIURA: "Piura",
  PUNO: "Puno",
  "SAN MARTIN": "San Martín",
  TACNA: "Tacna",
  TUMBES: "Tumbes",
  UCAYALI: "Ucayali",
};
